https://github.com/zergtant/pytorch-handbook/blob/master 参考连接

In [2]:
import torch
torch.__version__

'1.13.1+cpu'

In [3]:
x = torch.rand(5, 3)

In [4]:
x

tensor([[0.8953, 0.8458, 0.6212],
        [0.7736, 0.1803, 0.4576],
        [0.9736, 0.3140, 0.4775],
        [0.8411, 0.9982, 0.2590],
        [0.2216, 0.6742, 0.6424]])

In [6]:
torch.empty(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.Tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)

In [10]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x, dtype=torch.float)

In [12]:
x

tensor([[ 0.4806, -0.0858, -0.6857],
        [-0.7575,  0.2227, -0.0644],
        [-0.1529,  0.5056,  0.5356],
        [-0.2002,  1.0130,  0.9719],
        [-0.7900,  0.6838,  0.5410]])

In [15]:
x.shape[0], x.shape

(5, torch.Size([5, 3]))

In [20]:
y = torch.rand(5,3)

In [21]:
y

tensor([[0.6229, 0.5235, 0.9229],
        [0.5951, 0.3728, 0.7890],
        [0.0166, 0.0745, 0.4473],
        [0.7350, 0.1570, 0.5972],
        [0.6318, 0.0767, 0.2166]])

In [22]:
x + y

tensor([[ 1.1035,  0.4377,  0.2372],
        [-0.1625,  0.5955,  0.7246],
        [-0.1363,  0.5800,  0.9830],
        [ 0.5348,  1.1700,  1.5691],
        [-0.1582,  0.7605,  0.7576]])

In [23]:
x,y

(tensor([[ 0.4806, -0.0858, -0.6857],
         [-0.7575,  0.2227, -0.0644],
         [-0.1529,  0.5056,  0.5356],
         [-0.2002,  1.0130,  0.9719],
         [-0.7900,  0.6838,  0.5410]]),
 tensor([[0.6229, 0.5235, 0.9229],
         [0.5951, 0.3728, 0.7890],
         [0.0166, 0.0745, 0.4473],
         [0.7350, 0.1570, 0.5972],
         [0.6318, 0.0767, 0.2166]]))

In [24]:
y.add_(x)

tensor([[ 1.1035,  0.4377,  0.2372],
        [-0.1625,  0.5955,  0.7246],
        [-0.1363,  0.5800,  0.9830],
        [ 0.5348,  1.1700,  1.5691],
        [-0.1582,  0.7605,  0.7576]])

In [25]:
x[:, 1]

tensor([-0.0858,  0.2227,  0.5056,  1.0130,  0.6838])

In [26]:
x = torch.rand(4,4)

In [29]:
x.view(-1)

tensor([0.5610, 0.0434, 0.6808, 0.4153, 0.0910, 0.9739, 0.1919, 0.8262, 0.5264,
        0.5687, 0.3949, 0.6002, 0.3846, 0.5546, 0.0721, 0.0939])

In [30]:
x.numpy()

array([[0.5609834 , 0.04338038, 0.68083745, 0.41533208],
       [0.0909996 , 0.97385365, 0.19194889, 0.8262149 ],
       [0.52636325, 0.5686931 , 0.39494044, 0.6001787 ],
       [0.3845927 , 0.55455536, 0.07212812, 0.09393036]], dtype=float32)