- torch.Tensor 是这个包的核心类。如果设置 .requires_grad 为 True，那么将会追踪所有对于该张量的操作。当完成计算后通过调用 .backward()， 自动计算所有的梯度，这个张量的所有梯度会自动积累到 .grad 属性
- Tensor 和 Function互相连接并生成一个非循环图，它表示和存储了完整的计算历史。 每个张量都有一个.grad_fn属性，这个属性引用了一个创建了Tensor的Function（除非这个张量是用户手动创建的，即，这个张量的 grad_fn 是 None）

In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [6]:
y, y.grad_fn

(tensor([[3., 3.],
         [3., 3.]], grad_fn=<AddBackward0>),
 <AddBackward0 at 0x18a083bc708>)

In [7]:
a = torch.randn(2, 3)
a = (a * 3) / (a - 1)
print(a.requires_grad)
a.requires_grad_(True) # 修改现有张量的 requires_grad 属性
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


# 梯度

反向传播 因为 out是一个纯量（scalar），out.backward() 等于out.backward(torch.tensor(1))。

In [9]:
b.backward()

In [15]:
a.grad

tensor([[-7.5878e+00,  4.8204e+01, -2.1241e+00],
        [ 3.4004e-02,  4.4580e+00,  4.3583e+01]])

In [17]:
x = torch.randn(3, requires_grad=True)
y = x ** 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([129.7422, 860.3254, 519.4777], grad_fn=<MulBackward0>)


In [19]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([-1.0309e+02,  2.6548e+03, -2.0629e-01])
