# 2 预备知识

## 2.1 数据曹祖

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)

In [3]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [4]:
x.shape

TensorShape([12])

In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [8]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [9]:
tf.random.uniform((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.8226247 , 0.70869434, 0.15663719, 0.82590413],
        [0.6361418 , 0.37290657, 0.09901857, 0.84918916],
        [0.1308366 , 0.16015041, 0.4583999 , 0.1519376 ]],

       [[0.9229219 , 0.74498093, 0.36823535, 0.7960671 ],
        [0.7759882 , 0.41972876, 0.83587253, 0.483608  ],
        [0.8157902 , 0.23192906, 0.44485462, 0.23058903]]], dtype=float32)>

In [10]:
tf.constant([[2,3,4], [3,2,1], [3,4,5]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 2, 1],
       [3, 4, 5]])>

In [13]:
x = tf.constant([[1.0, 2, 4, 8],[2.0, 2, 2, 2]])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 3.,  4.,  6., 10.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-1.,  0.,  2.,  6.],
        [ 0.,  0.,  0.,  0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 2.,  4.,  8., 16.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0.5, 1. , 2. , 4. ],
        [1. , 1. , 1. , 1. ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 1.,  4., 16., 64.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>)

In [14]:
tf.exp(x)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
       [7.3890562e+00, 7.3890562e+00, 7.3890562e+00, 7.3890562e+00]],
      dtype=float32)>

In [28]:
x = tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
y = tf.constant([[2.,1,4,3], [1,2,3,4], [3,4,2,1]])
tf.concat([x,y], axis=0),tf.concat([x,y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  3.,  4.,  2.,  1.]], dtype=float32)>)

In [29]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [30]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [31]:
x[-1], x[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [33]:
x_var = tf.Variable(x)
x_var[1,2].assign(9)
x_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [34]:
before = id(y)
y = y+x
id(y) == before

False

In [37]:
z = tf.Variable(tf.zeros_like(y))
print(id(z))
z.assign(x + y)
print(id(z))

1675017582152
1675017582152


In [38]:
a = x.numpy()
b = tf.constant(a)
type(a), type(b)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

## 2.2 数据预处理

## 2.3 线性代数

In [39]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [41]:
print(len(x))
x.shape

4


TensorShape([4])

In [42]:
A = tf.reshape(tf.range(20), (5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [44]:
A[:,0]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0,  4,  8, 12, 16])>

In [45]:
A[0]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [47]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

In [48]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
B = A
A, A+B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [50]:
id(A) == id(B)

True

In [51]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

In [52]:
a = 2
A + a

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.],
       [14., 15., 16., 17.],
       [18., 19., 20., 21.]], dtype=float32)>

In [53]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)

In [55]:
A_sum_axis0 = tf.reduce_sum(A, axis=0)
A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>,
 TensorShape([4]))

In [57]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>

In [58]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [59]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [60]:
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [61]:
A / A_sum_axis0

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.02222222, 0.04      , 0.05454545],
       [0.1       , 0.11111111, 0.12      , 0.12727273],
       [0.2       , 0.2       , 0.2       , 0.2       ],
       [0.3       , 0.2888889 , 0.28      , 0.27272728],
       [0.4       , 0.37777779, 0.36      , 0.34545454]], dtype=float32)>

In [62]:
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

In [63]:
tf.cumsum(A, axis=1)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  3.,  6.],
       [ 4.,  9., 15., 22.],
       [ 8., 17., 27., 38.],
       [12., 25., 39., 54.],
       [16., 33., 51., 70.]], dtype=float32)>

In [70]:
y = tf.ones(4, dtype=tf.int32)
x, y, tf.tensordot(x, y, axes=1)

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [68]:
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [71]:
x*y

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [82]:
x = tf.range(4, dtype=tf.float32)
A.shape, x.shape, tf.linalg.matvec(A, x)

(TensorShape([5, 4]),
 TensorShape([4]),
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>)

In [84]:
x, A

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>)

In [85]:
B = tf.ones((4,3), tf.float32)
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>

In [87]:
u = tf.constant([3.0,-4])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [88]:
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>