In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)

In [3]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [4]:
x.shape

TensorShape([12])

In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [8]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [9]:
tf.random.uniform((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.8226247 , 0.70869434, 0.15663719, 0.82590413],
        [0.6361418 , 0.37290657, 0.09901857, 0.84918916],
        [0.1308366 , 0.16015041, 0.4583999 , 0.1519376 ]],

       [[0.9229219 , 0.74498093, 0.36823535, 0.7960671 ],
        [0.7759882 , 0.41972876, 0.83587253, 0.483608  ],
        [0.8157902 , 0.23192906, 0.44485462, 0.23058903]]], dtype=float32)>

In [10]:
tf.constant([[2,3,4], [3,2,1], [3,4,5]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 2, 1],
       [3, 4, 5]])>