In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)

In [3]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [4]:
x.shape

TensorShape([12])

In [6]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [8]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [9]:
tf.random.uniform((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0.8226247 , 0.70869434, 0.15663719, 0.82590413],
        [0.6361418 , 0.37290657, 0.09901857, 0.84918916],
        [0.1308366 , 0.16015041, 0.4583999 , 0.1519376 ]],

       [[0.9229219 , 0.74498093, 0.36823535, 0.7960671 ],
        [0.7759882 , 0.41972876, 0.83587253, 0.483608  ],
        [0.8157902 , 0.23192906, 0.44485462, 0.23058903]]], dtype=float32)>

In [10]:
tf.constant([[2,3,4], [3,2,1], [3,4,5]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 2, 1],
       [3, 4, 5]])>

In [13]:
x = tf.constant([[1.0, 2, 4, 8],[2.0, 2, 2, 2]])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 3.,  4.,  6., 10.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[-1.,  0.,  2.,  6.],
        [ 0.,  0.,  0.,  0.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 2.,  4.,  8., 16.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0.5, 1. , 2. , 4. ],
        [1. , 1. , 1. , 1. ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 1.,  4., 16., 64.],
        [ 4.,  4.,  4.,  4.]], dtype=float32)>)

In [14]:
tf.exp(x)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
       [7.3890562e+00, 7.3890562e+00, 7.3890562e+00, 7.3890562e+00]],
      dtype=float32)>

In [28]:
x = tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
y = tf.constant([[2.,1,4,3], [1,2,3,4], [3,4,2,1]])
tf.concat([x,y], axis=0),tf.concat([x,y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  3.,  4.,  2.,  1.]], dtype=float32)>)

In [29]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [30]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [31]:
x[-1], x[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [33]:
x_var = tf.Variable(x)
x_var[1,2].assign(9)
x_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [34]:
before = id(y)
y = y+x
id(y) == before

False

In [37]:
z = tf.Variable(tf.zeros_like(y))
print(id(z))
z.assign(x + y)
print(id(z))

1675017582152
1675017582152


In [38]:
a = x.numpy()
b = tf.constant(a)
type(a), type(b)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)